create table blogful_comments (
    id integer primary key generated by default as identity,
    text text not null,
    date_commented TIMESTAMPTZ default now() not null,
    article_id integer
        references blogful_articles(id) on delete cascade not null,
    user_id integer
        references blogful_users(id) on delete cascade not null
);